### ISSUE TITLE
App Store rejection due to react-native-onesignal

### ISSUE THREAD

**Issue by ilyakar** [OneSignal/react-native-onesignal#1060] opened 2020-10-20 13:43 UTC
When the library is not included and installed, the app is accepted fine. Once I add it then Apple rejects it :/

Having talked to Apple over the phone, the problem lies purely in their algorithms giving a false positive of the IDFA usage.
Can the code be updated somehow in react-native-onesignal to solve this?

![image](https://user-images.githubusercontent.com/1760709/96594113-2ce44b80-12e2-11eb-9116-97883c2efbc8.png)

_Originally posted by @ilyakar in https://github.com/OneSignal/react-native-onesignal/issues/1029#issuecomment-712859418_

**Comment by rgomezp** [comment] 2020-10-20 19:50
Duplicate of #1029

**Closed as completed by rgomezp** 2020-10-20 19:50 UTC
