### ISSUE TITLE
Crash in android 6.0.1 while receiving In app message.  

### ISSUE THREAD

**Issue by thisisbalaG** [OneSignal/react-native-onesignal#867] opened 2019-09-20 11:56 UTC
Hi, 

I have a crash issue while receiving in-app notification in a particular Android device.

Android 6.0.1 Samsung phone SM-J700F API 23.

But It works perfectly in all other devices. Need a solution for this.

I'm not getting any logs or error message while debugging. The app just crashes.

Please help.

**Comment by rgomezp** [comment] 2019-09-23 23:09
Duplicate of #863

**Closed as completed by rgomezp** 2019-09-23 23:09 UTC
