### ISSUE TITLE
In App Message Crash on IOS using one signal IOS SDK 2.11.2

### ISSUE THREAD

**Issue by avent08** [OneSignal/react-native-onesignal#896] opened 2019-11-08 13:21 UTC
**Description:**
I already implement the one signal configuration to enable in app message using this docs.
https://documentation.onesignal.com/docs/in-app-quickstart
The in app message successfully appeared, after the modal closed, wait for 10-20 seconds, then the app will start freeze then force closed. This bug only happen when user click any button on the modal, but if user just let the modal dissapear then it wont trigger the force close.

**Environment**
1. One signal React Native SDK 3.4.2
2. One signal IOS SDK 2.11.2
3. Adding SDK using yarn install and do manual linking on Podfile

**Steps to Reproduce Issue:**
1. Install and config your react native one signal SDK like on the docs
2. Open your app
3. Wait until in app message popup appear
4. Click cancel or click any button to make the modal dissapear
5. Wait for a while then app will freeze, then force close

**Anything else:**
Crash Log :
WARNING: GoogleAnalytics 3.17 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:48): Uncaught exception: *** -[__NSSetM addObject:]: object cannot be nil

In our app we dont manually call any google analytics. and the crash only happen when the in app message appear.

**Comment by rgomezp** [comment] 2019-11-08 23:33
Howdy,
We're aware of this issue and are currently investigating. Thanks for your patience

**Comment by rgomezp** [comment] 2019-11-11 22:07
Duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/issues/542

**Closed as completed by rgomezp** 2019-11-11 22:07 UTC
