### ISSUE TITLE
OneSignalNotificationServiceExtension fails to build in XCode with SDK 3.4.1

### ISSUE THREAD

**Issue by bkraeling** [OneSignal/react-native-onesignal#866] opened 2019-09-19 17:31 UTC
**Description:**

I'm getting the following error after trying to upgrade my SDK version to 3.4.1 (to support iOS 13).
<img width="865" alt="Screen Shot 2019-09-19 at 12 24 50 PM" src="https://user-images.githubusercontent.com/6200068/65266657-7cee4e80-dae1-11e9-95ba-4e0f2475d1f7.png">

**Environment**
SDK version 3.4.1
React Native version 59.9
**Note: This builds in SDK version 3.3.3**

**Steps to Reproduce Issue:**

1. Set up OneSignal SDK with OneSignalNotificationServiceExtension
2. Upgrade to 3.4.1
3. Attempt to build in XCode

**Comment by rgomezp** [comment] 2019-09-19 21:23
Duplicate of #856

**Closed as completed by rgomezp** 2019-09-19 21:23 UTC
