### ISSUE TITLE
Redmi notification cannot open app

### ISSUE THREAD

**Issue by komelabbbas** [OneSignal/react-native-onesignal#1381] opened 2022-04-25 13:47 UTC
Description:
Xiaomi notification cannot open the app due to permissions. As far as I have researched, it is necessary to allow "display pop-up window in the foreground and in the background" from the application settings.

Environment
Device: Redmi 9 Power
Package version: 4.3.8

Steps to Reproduce Issue:

close your app
send your notification
open notification (app not opening)

**Comment by komelabbbas** [comment] 2022-04-25 13:48
Any solutions for this?, plz help.

**Comment by komelabbbas** [comment] 2022-04-25 13:49
```
Linking.sendIntent(
      'miui.intent.action.APP_PERM_EDITOR', 
      [
        {'com.miui.securitycenter': 'com.miui.permcenter.permissions.PermissionsEditorActivity'},
        {'extra_pkgname': 'com.myapp'}
      ]
    )
```

I have tried this, but it redirects every time when the app starts.😞

**Comment by jkasten2** [comment] 2022-04-25 17:51
@komelabbbas There is a issue for the Android-OneSignal-SDK (that this library uses under the hood) about this Xiaomi specific problem.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/1494

**Comment by jkasten2** [comment] 2022-04-25 18:17
Closing this as duplicate of issue https://github.com/OneSignal/react-native-onesignal/issues/1309

**Closed as completed by jkasten2** 2022-04-25 18:17 UTC
