### ISSUE TITLE
Android build for detox tests fails after update from 3.1.2 to 3.2.4

### ISSUE THREAD

**Issue by kormang** [OneSignal/react-native-onesignal#585] opened 2018-07-16 09:19 UTC
**Description:**

After updating from 3.1.2 to 3.2.4, building detox E2E tests fails.
ONLY when building for detox tests there were few problems with some dependencies, first of which appeared this one:

<pre>
> Task :react-native-onesignal:compileDebugJavaWithJavac
Note: /Users/marko/Develop/cp-mobile/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

What went wrong:

Execution failed for task ':app:preDebugAndroidTestBuild'.
> Conflict with dependency 'com.android.support:exifinterface' in project ':app'. Resolved versions for app (27.0.2) and test app (26.1.0) differ. See https://d.android.com/r/tools/test-apk-dependency-conflicts.html for details.
</pre>

These problems with dependecies I have fixed, one by one, by making these changes to app/build.gradle:
<pre>
-    compileSdkVersion 26
-    buildToolsVersion "26.0.2"
+    compileSdkVersion 27
+    buildToolsVersion "27.0.2"
-        targetSdkVersion 26
+        targetSdkVersion 27

-    implementation ('com.android.support:exifinterface:26.1.0') {
-        force = true
-    }

-    implementation "com.android.support:appcompat-v7:23.0.1"
-    implementation 'com.facebook.android:facebook-android-sdk:4.22.1'
+    implementation ('com.facebook.android:facebook-android-sdk:4.22.1')
+    implementation 'com.google.android.gms:play-services-auth:15.0.1'
+    implementation 'com.google.android.gms:play-services-vision:15.0.2'
+    implementation 'com.google.android.gms:play-services-location:15.0.1'
+    implementation 'com.google.firebase:firebase-messaging:15.0.2'
+    implementation 'com.android.support:support-v4:27.0.2'
+    implementation 'com.android.support:cardview-v7:27.0.2'
+    implementation 'com.android.support:appcompat-v7:27.0.2'
+    implementation 'com.android.support:customtabs:27.0.2'

</pre>

But even after that I had this problem:

<pre>
> Task :react-native-onesignal:processDebugAndroidTestManifest
/Users/kormang/project/node_modules/react-native-onesignal/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger7547925283700485124.xml Error:
        Attribute meta-data#onesignal_app_id@value at manifestMerger7547925283700485124.xml requires a placeholder substitution but no value for <onesignal_app_id> is provided.
/Users/kormang/project/node_modules/react-native-onesignal/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger7547925283700485124.xml Error:
        Attribute meta-data#onesignal_google_project_number@value at manifestMerger7547925283700485124.xml requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.
</pre>

Returning **manifestPlaceholders** to app/build.gradle, where it was before update, does not help.

**Environment**
"react-native-onesignal": "3.1.2" BEFORE
"react-native-onesignal": "3.2.4", NOW
"react-native": "0.54.2"
"detox": "7.2.0"

<pre>
configurations: {
...
"android.emu.debug": {
"binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
"build": "export ENVFILE=.env.dev && cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
"type": "android.attached",
"name": "192.168.56.101:5555"
}
}
</pre>

compileSdkVersion 27 (tried with 26 first)
buildToolsVersion "27.0.2" (tried with "26.0.2" first)
targetSdkVersion 27 or (tried with 26 first)

 Gradle: 4.1

**Steps to Reproduce Issue:**
1. Change version numbers in **package.json** i run **yarn.**
2. Follow instruction from [Setup Guide](https://documentation.onesignal.com/v5.0/docs/react-native-sdk-setup), and removed code, like **manifestPlaceholders**, that is no longer needed.
3. clean everything and run `detox build -c android.emu.debug`

**Anything else:**

I'm not native android developer and my knowledge of its build system is limited, but I'm trying.

My team decided to stick to older version for now, as it works perfectly well. We hope that these issues will be resolved, and that we could enjoy new features and API that new version brings.
Any help or suggestion will be appreciated.

**Comment by Nightsd01** [comment] 2018-07-16 18:01
Closing because this is a duplicate of #579. We are aware of this issue and are definitely working to resolve it. Thank you for posting such a detailed bug report!

**Closed as completed by Nightsd01** 2018-07-16 18:01 UTC

**Comment by kormang** [comment] 2018-07-16 20:10
Sorry, I've found that issue, but did not notice that they are duplicates, that is, I did not notice that it is also about detox ans tests.
