### ISSUE TITLE
Outdated Android Supported Library

### ISSUE THREAD

**Issue by dilawer** [OneSignal/react-native-onesignal#1050] opened 2020-09-28 13:25 UTC
**Description:**
I have followed the instructions carefully and exactly the same way mentioned at the [link](https://documentation.onesignal.com/docs/react-native-sdk-setup). However at the dashboard of onesignal, I see against my testing device it is shown "Outdated Android Supported Library". What else am I missing? Any help would be highly appreciated.

**Environment**
My gradle version:
6.1.1
My project level build.gradle:
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'
    }
}
My app level build.gradle:
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28

```
}
```

}
My react-native version in package.json
    "react-native": "0.61.2",
My AndroidManifest.xml
<activity>
...
    android:launchMode="singleTask"
...
</activity>

**Comment by rgomezp** [comment] 2020-09-28 20:25
Duplicate of #455 

To give you some more technical details, the targetSdkVersion and the Android Support library version of the app must match.

Also see: 
- https://github.com/OneSignal/OneSignal-Android-SDK/issues/553
- https://github.com/OneSignal/OneSignal-Android-SDK/issues/674

**Comment by rgomezp** [comment] 2020-10-27 00:29
Closing due to no response

**Closed as completed by rgomezp** 2020-10-27 00:29 UTC
Labels: Android
