### ISSUE TITLE
androidTest directory is causing issues with Detox 

### ISSUE THREAD

**Issue by mtt87** [OneSignal/react-native-onesignal#787] opened 2019-07-02 16:09 UTC
**Description:**
This is kinda related to https://github.com/geektimecoil/react-native-onesignal/issues/579
I had to use the hack suggested there, so it feels like this is still an ongoing issue.

That said, there is also a problem with the `androidTest` directory which I believe it's used to run tests during development (sorry not Android expert)

That produces an error when trying to build the app for testing using [Detox](https://github.com/wix/Detox)
```
> Task :react-native-onesignal:compileDebugAndroidTestJavaWithJavac FAILED
/Users/masti/Dev/app-job-mobile/node_modules/react-native-onesignal/android/src/androidTest/java/com/geektime/rnonesignalandroid/ApplicationTest.java:4: error: package android.test does not exist
import android.test.ApplicationTestCase;
                   ^
/Users/masti/Dev/app-job-mobile/node_modules/react-native-onesignal/android/src/androidTest/java/com/geektime/rnonesignalandroid/ApplicationTest.java:9: error: cannot find symbol
public class ApplicationTest extends ApplicationTestCase<Application> {
                                     ^
  symbol: class ApplicationTestCase
2 errors
```

This is weird cause I've never seen any react native android dependency with the `androidTest` folder included in the package.

Removing the `androidTest` directory entirely makes the build succeed.

So I wonder: **is this directory necessary to be included in the npm package or can it only live in the GitHub repo?**

**Environment**
```
"react-native": "^0.59.9",
"react-native-onesignal": "^3.2.14",
```

**Steps to Reproduce Issue:**

1. Init a new RN project
2. `npm i --save react-native-onesignal` and go through the installation
3. Add Detox (follow Android installation) https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#setup-gear

Thank you 😄

**Comment by sonicdoe** [comment] 2019-07-02 19:01
By the way, this is also related to #777. It doesn’t mention Detox specifically but Detox (usually) executes `assembleAndroidTest`.

**Comment by mtt87** [comment] 2019-07-02 19:05
@sonicdoe would you be able to answer my question?
> is this directory necessary to be included in the npm package or can it only live in the GitHub repo?

Because if the answer is no, then **this** problem is solved for me.

I'm asking because I don't know what are good practices but I don't see other RN packages with this directory `androidTest` so I guess either nobody is testing or they don't include tests in the npm package?

**Comment by sonicdoe** [comment] 2019-07-02 19:22
I’m confident that you can fully remove the `android/src/androidTest` directory. It only contains the [`ApplicationTest`](https://github.com/geektimecoil/react-native-onesignal/blob/c8cf6555fb2d0d51500e12b7e40f0633b818c293/android/src/androidTest/java/com/geektime/rnonesignalandroid/ApplicationTest.java) class which seems to be boilerplate probably generated by Android Studio at one point. Its introduction even goes back to the very first commit in [`1b597f5`](https://github.com/geektimecoil/react-native-onesignal/commit/1b597f566af5884a0ef57b22d336936c45fa3b5e#diff-a4930124cb29c1b841f4ab771a7b5434).

**Comment by rgomezp** [comment] 2019-07-02 19:33
Thanks for opening, but this is a duplicate of #777 so will close here. Please continue the conversation there!

**Closed as completed by rgomezp** 2019-07-02 19:33 UTC
