### ISSUE TITLE
How to disable the "Open Website?" alert, when payload includes launchURL

### ISSUE THREAD

**Issue by Salar-g** [OneSignal/react-native-onesignal#1140] opened 2021-01-10 01:17 UTC
**Description:**
I have a launchURL in my notification payload. LaunchURL is used for navigating to a specific page using deep linking. However every time a notification is received, an Alert also pops-up that says "Open Website? Would you like to open myApp:main..". The deep-linking works as expect. I wonder if there is was prevent this Alert to pop-up.

(your description here)

**Environment**
"react-native-onesignal": "^3.6.4",
"react-native": "0.61.2",

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using npm into your project
1. add deep linking
1. send a notification with launchURL
1. the below notification will be shown

![Screen Shot 2021-01-09 at 8 16 48 PM](https://user-images.githubusercontent.com/44076735/104112036-b68b3000-52b7-11eb-9d6f-e607182e36c5.png)

Related: #1016

**Comment by rgomezp** [comment] 2021-01-13 21:09
Duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1140

**Comment by dickfickling** [comment] 2021-01-30 04:41
@rgomezp you closed this as a duplicate of #1140 (which is... this ticket). Did you mean it's a dupe of OneSignal/OneSignal-iOS-SDK#777? just want to make sure the work to fix it is being tracked.

**Comment by rgomezp** [comment] 2021-01-30 04:50
Yes. It was a mistake. Thanks for pointing that out.

**Comment by stu-dev** [comment] 2021-02-18 20:28
Hi @rgomezp, I don't think this is technically a duplicate of the iOS issue [#777](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/777). 

The iOS issue wants to disable the "Open Website" alert so that the deeplink it could be handled natively, whereas on the React Native side I'm assuming most of us just want it to **automatically** open the deeplink without the alert? It seems like 2 different expected behaviours.

**Comment by leethree** [comment] 2021-02-19 11:41
Yes I just disabled the iOS prompt now deep linking no longer works automatically. 

I tried to manually handle `launchURL` in `setNotificationOpenedHandler` but it doesn't seem to work on cold launch from notification.

**Comment by tomwhale** [comment] 2021-02-19 22:22
Still seeing this issue! The alerts have gone, but deep linking isn't working. If you have any hints on how to fix it @rgomezp I am happy to do a PR.

Thanks!

**Comment by rgomezp** [comment] 2021-02-22 19:08
Howdy everyone,
We did resolve the native SDK issue 777 in the [latest release](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.0.4) which updates the underlying native iOS SDK to the version with the fix.

@stu-dev can you please upgrade and try that release to see if the issue is resolved?

**Comment by tomwhale** [comment] 2021-02-22 19:12
@rgomezp I can confirm the Alert no longer shows, but deep linking does not work.

**Comment by stu-dev** [comment] 2021-02-25 08:33
Hi @rgomezp to echo what @tomwhale said - on upgrade the message disappears but now deep linking does not work properly

**Comment by rgomezp** [comment] 2021-02-25 15:47
Thanks everyone for the info.

@gonzalonarbaiz is investigating.

To confirm, this deep linking issue was not occurring for you prior to the alert issue correct?

**Comment by tomwhale** [comment] 2021-03-02 10:15
Hi,

It was happening before. From the app closed state, the deep linking did not work. 

Something was released which caused the alert prompt when deeplinking. Deeplinking worked, but we had the alert which was not ideal.

Then another fix went out which fixed the alert, but deep linking no longer works again.

**Comment by azai91** [comment] 2021-03-03 17:15
Any update on this?

**Comment by rgomezp** [comment] 2021-03-03 21:18
Closes #1016

**Comment by rgomezp** [comment] 2021-03-03 21:19
Related: #1016 
---

**Comment by rgomezp** [comment] 2021-03-03 21:27
Howdy,
Since the alert is resolved, I will close this issue.

The deeplinking issue is covered by #1016 . Please continue tracking the issue there.

**Closed as completed by rgomezp** 2021-03-03 21:27 UTC
Labels: Help Wanted, iOS
