### ISSUE TITLE
External user id is not populating when installing the app on iOS device and calling OneSignal.setExternalUserId method 

### ISSUE THREAD

**Issue by Shashank123sprive** [OneSignal/react-native-onesignal#1181] opened 2021-03-05 08:46 UTC
Hi Team,

I've developed one app, which is using one signal for push notifications, and from past few days I'm facing one issue on iOS platform, the external user id is not populating for my player id. I haven't changed anything, neither in my source code or in one signal configuration.

Actually when we're installing the app(on iOS device with OneSignal SDK configured i.e **react-native-onesignal- ^3.6.3**) the device session is getting populated in one signal's dashboard under **Audience->All Users**, but the external user id is not populating for my player id. **I have set the log level to verbose in order to check the what is happening when I'm initiating the one signal listener, and setting the one signal external user id, but I can see that the one signal app id which I've defined in the AppDelegate.m file (**813aa25-8bd8-41e5-9d3f-387e6XXXX**)is not matching with the one signal app id which is coming in the log i.e at the following line:**

VERBOSE:HTTP Request (OSRequestRegisterUser) with URL: https://api.onesignal.com/players, with parameters: {
"app_id" : "405f33b8-ab67-4f30-95ab-75182574XXS",
"net_type" : 0,
"test_type" : 1,
"ios_bundle" : "com.sprive.mobile.ios",
"device_type" : 0,
"sdk_type" : "react",
"sdk" : "021601",
"identifier" : "IIIIIIIIII",
"language" : "en-IN",
"device_os" : "12.4.2",
"game_version" : "8",
"timezone" : 19800,
"ad_id" : "XXXXXXXX",
"notification_types" : 31,
"device_model" : "iPhone6,2",
"carrier" : "AirTel"
}

VERBOSE: network response (OSRequestRegisterUser): {
    errors =     (
        "App with id: 405f33b8-ab67-4f30-95ab-75182574XXS does not exist"
    );
}

So, at the above line I can see the app id is different than the one I've defined in AppDelegate.m which is correct wrt the app I've created in one signal platform. FYI the same code base is working fine in android platform.

Would you please let me know what is the reason behind the external user id not appearing, and due to this I can't send push notifications to the subscribed users(on iOS platform). FYI in case of android platform with the same codebase the external user id is getting populated:

The code to set the external user id :

OneSignal.setExternalUserId(myExternalUserID);

It would be really helpful, if you can help me to resolve this.

**Comment by VasylRomanets-MoonActive** [comment] 2021-03-30 10:24
@Shashank123sprive, hi! I had the same problem on iOS but with OneSignal Unity SDK. I tried to call `OneSignal.setExternalUserId()` API after user accepted push notifications with the default system prompt and it worked for me.

**Comment by rgomezp** [comment] 2021-03-31 23:09
Howdy,
Thanks for your patience.

This is a duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/issues/865

Thanks @VasylRomanets-MoonActive for your community suggestion!

This issue has since been fixed in the latest version of the SDK. Please upgrade to get the fix!

Enjoy!

**Closed as completed** 2021-03-31 23:11 UTC
Labels: iOS
