### ISSUE TITLE
getDeviceState delay in getting the userId and pushToken

### ISSUE THREAD

**Issue by sktan810** [OneSignal/react-native-onesignal#1191] opened 2021-03-26 10:00 UTC
**Description:**
Calling getDeviceState when app fires, in normal situation it will returns 

 _{ 
  isEmailSubscribed: boolean,
  isSubscribed: boolean,
  pushToken: string,
  isPushDisabled: boolean,
  userId: string,
  hasNotificationPermission: boolean 
},_

However, it seems like have to wait at least 30 seconds to get the userId and pushToken in Android (GMS) and iOS.
Even **worst** in **Android (HMS)**, it does not return userId and pushToken values. 
It only returns those values when I close and restart the app in HMS.
Now i have to make it delays for 30seconds and call it instead of keep calling getDeviceState.

**Environment**
"react-native-onesignal": "^4.0.5",
"react-native": "^0.62.2",
"react": "16.9.0",

**Steps to Reproduce Issue:**

1.  Open app
1. OneSignal.setAppId(ONESIGNAL_ID);
1. const deviceState = await OneSignal.getDeviceState();
1. OneSignal.setNotificationWillShowInForegroundHandler
1. OneSignal.setNotificationOpenedHandler

**Comment by rgomezp** [comment] 2021-03-31 23:12
Duplicate of #1159

**Closed as completed by rgomezp** 2021-03-31 23:12 UTC
