### ISSUE TITLE
Does OneSignal use advertisingIdentifier (IDFA)? [submitting for App Store review] [advertising identifier] (potential Apple rejection from store)

### ISSUE THREAD

**Issue by luckytiger1** [OneSignal/react-native-onesignal#1029] opened 2020-07-31 03:53 UTC
**Description:**

I'm gonna publish my app to App Store, but I'm not sure if my app uses advertisingIdentifier.

I tried to use "find . | grep -v .svn | grep "\.a" | grep -v "\.app" | xargs grep advertisingIdentifier" to find files that include advertisingIdentifier inside of it.

Output:

Binary file ./node_modules/react-native-onesignal/ios/libOneSignal.a matches
grep: ./node_modules/object.assign: Is a directory
grep: ./node_modules/object.assign/test: Is a directory
grep: ./node_modules/object.assign/dist: Is a directory

Screenshot of other searches for advertisingIdentifier in project directory:

![image](https://user-images.githubusercontent.com/54556004/88998557-231aff80-d314-11ea-9896-f33117ed3c64.png)

If it uses advertisingIdentifier, what options should i choose before publishing, and I'm not going to display any ad for now.

Here are possible options:

![image](https://user-images.githubusercontent.com/54556004/88998926-f4e9ef80-d314-11ea-9da4-90a6043dd8ec.png)

**Environment**

"react-native": "0.62.2",
"react-native-onesignal": "^3.9.0"

**Comment by rgomezp** [comment] 2020-08-25 22:30
Howdy,
This is a great question. I see we have answered this in the [past](https://twitter.com/onesignal/status/725368560067846144) but could have provided more elaboration.

First of all, we only use IDFA if the app already uses it ([source](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/e1b89402016958a4b4402078f2222f1a603061ad/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L1710)). This means the OneSignal SDK isn't a factor on needing to check that box when submitting to Apple.

**What does OneSignal use IDFA for?**
We use IDFA (if already in use) to prevent duplicate records if someone re-installs the app. Furthermore, if the user opts out of IDFA on the device level we also respect that setting and don't use it at all.

@luckytiger1 
So in your case, if no other SDK you are using uses it and you're not using it yourself, you don't have to check the box.
I hope this helps answer your question.

**Edit:**
Please double check that you don't have the `AdSupport.framework` anywhere in your Xcode project since this would trigger this as well.

Note that we plan to remove IDFA support right after the next major release (version 3.0+) so keep an eye out for that one.

Enjoy using OneSignal!

**Comment by ilyakar** [comment] 2020-10-15 13:04
@rgomezp it seems that Apple isn't smart enough to figure out the plugin isn't using IDFA. Apple is rejecting our app when react-native-onesignal is installed due to "IDFA usage" :/

I think we should open this issue and investigate further.

![image](https://user-images.githubusercontent.com/1760709/96130436-d6e16380-0eef-11eb-96f5-62e4a01de938.png)


![image](https://user-images.githubusercontent.com/1760709/96130410-ccbf6500-0eef-11eb-8519-55d23851fdab.png)

**Comment by ilyakar** [comment] 2020-10-15 13:05
![image](https://user-images.githubusercontent.com/1760709/96130178-76eabd00-0eef-11eb-9052-62268ca366ca.png)

**Comment by rgomezp** [comment] 2020-10-16 19:57
@ilyakar ,
Please double check that you don't have the `AdSupport.framework` anywhere in your Xcode project since this would trigger this as well.

**Comment by ilyakar** [comment] 2020-10-16 21:37
I don’t :/ It was the first thing I removed but Apple is still complaining.

**Comment by ilyakar** [comment] 2020-10-20 13:41
Confirmed, App Store rejection happening due to OneSignal plugin.
![image](https://user-images.githubusercontent.com/1760709/96594113-2ce44b80-12e2-11eb-9116-97883c2efbc8.png)

I'll open a new issue.

**Comment by wassimseif** [comment] 2020-10-26 08:13
@rgomezp Thank you for your help 

For OneSignal/OneSignal-iOS-SDK/issues/778 
I made sure that `AdSupport.framework` is not linked anywhere in my Xcode project However the IDFA collection rejection error is still there.

Also, I guess release 4.0 is still far away since the latest release of the iOS SDK is still 3.0 beta2.
Is there anyway we can fix this issue with the current release of the SDK?

**Comment by rgomezp** [comment] 2020-10-26 19:23
Howdy @wassimseif ,
That was a typo. I meant to write 3.0 for the iOS native SDK major release version. At the moment I don't know that there is a way to fix the issue without a change to the SDK itself. We will investigate potential workarounds but as of now, we just kindly ask for your patience until we get out the release.

For anyone wanting a challenge, feel free to make an open-source contribution to the iOS Native SDK with the fix.

---
cc @emawby

**Comment by ilyakar** [comment] 2020-10-28 12:45
Thank you @rgomezp. For now, I removed all references of OneSignal to get our app into the stores. Looking forward to hearing from you when you guys manage to get the fix out.

From my digging, it seems that the SDK does indeed need to be updated to remove all references of `advertisingIdentifier` which Apple is looking for.

**Comment by wassimseif** [comment] 2020-10-29 07:58
@ilyakar Is there any drawbacks you noticed after removing this ?

**Comment by ilyakar** [comment] 2020-11-13 18:13
@rgomezp what is the current workaround to get the react-native version of OneSignal + iOS Onesignal without the IDFA collection?

**Comment by rgomezp** [comment] 2020-12-10 20:59
Howdy,
We have removed the use of IDFA in the iOS major-release. It will be a part of the beta 5 version of the RN SDK which will go out of beta very soon. There are no drawbacks from removing this.

Thanks for your patience.

**Comment by rgomezp** [comment] 2021-01-11 22:42
Howdy,
This has now been resolved in the last major release.

Enjoy!

**Closed as completed by rgomezp** 2021-01-11 22:42 UTC
