### ISSUE TITLE
[Bug]: Instant Crash on iOS

### ISSUE THREAD

**Issue by StephenTANM** [OneSignal/react-native-onesignal#1512] opened 2023-04-12 21:53 UTC
### What happened?

After following the setup steps here: https://documentation.onesignal.com/docs/react-native-sdk-setup

I build the projects and it crashes on splash screen with this error:
<img width="729" alt="Screenshot 2023-04-12 at 3 50 42 PM" src="https://user-images.githubusercontent.com/20388011/231593987-c4b64625-4b19-408d-8af3-f2a67adf3710.png">

### Steps to reproduce?

```Markdown
1. Follow steps here: https://documentation.onesignal.com/docs/react-native-sdk-setup
2. Build project
3. Try to open the app
```

### What did you expect to happen?

I expected the app to not crash.

### React Native OneSignal SDK version

4.5.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
dyld[57486]: Library not loaded: @rpath/OneSignalExtension.framework/OneSignalExtension
  Referenced from: <AEEE42FE-8CAB-322A-8DFF-C0163A06731C> /private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/aveniciointl
  Reason: tried: '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/preboot/Cryptexes/OS@rpath/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/0C8A4F94-5AF4-42A4-AEB6-46CF383E3C6B/aveniciointl.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/System/Library/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache)
Message from debugger: Terminated due to signal 9
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment] 2023-04-12 22:17
This is likely a duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1459. There is discussion of fixes in that thread that could help!

**Closed as completed by emawby** 2023-04-12 22:17 UTC
Labels: Duplicate
