### ISSUE TITLE
Android: does not register device, oneSignalRestClient returns "Invalid device_type format! Expected integer"

### ISSUE THREAD

**Issue by ivanlyubimov** [OneSignal/react-native-onesignal#557] opened 2018-06-12 19:27 UTC
**Description:**
SDK doest not register device.

New device does not appear in dashboard device list.
Initialisation done specifying onesignal_app_id and onesignal_google_project_number in build.gradle.
Following logcat I noticed that there is request failing to onesignal api: 

`D/OneSignal: OneSignalRestClient: Making request to:
https://onesignal.com/api/v1/players/2d9e5e61-46c4-4080-8a81-d47455ecaa9f/on_session
D/OneSignal: OneSignalRestClient: POST SEND JSON:
{"app_id":"myonesignalappidhere"}
D/OneSignal: OneSignalRestClient: Failed request to:
https://onesignal.com/api/v1/players/2d9e5e61-46c4-4080-8a81-d47455ecaa9f/on_session
W/OneSignal: OneSignalRestClient: POST RECEIVED JSON:
{"errors":["Invalid device_type format! Expected integer"]}
W/OneSignal: Failed last request. statusCode: 400 response:
{"errors":["Invalid device_type format! Expected integer"]}`

Notably, after number of launches throughout an hour it returns 200 and registers new device. Without any code change

**Environment**
1. What version of the OneSignal React-Native SDK are you using?
3.1.4
2. How did you add the SDK to your project
npm

**Steps to Reproduce Issue:**
  1.  Install the OneSignal SDK using npm into your project
  2. Initialize the SDK in the android/build.gradle
  3. Launch app, see logcat, check dashboard for new device  

**Anything else:**
In attempt to find a way around the issue, I tried few different sdk versions as well as latest, but ultimately hit #516 or #515 every time

**Comment by Nightsd01** [comment] 2018-06-13 01:46
@ivanlyubimov Did you manually delete the user for this device in our dashboard? This would happen if you deleted a user _without_ uninstalling the app, because the app still has the old player_id saved locally.

In short, I'm pretty sure this happened because you either deleted the player id, or possibly because you have a mixup with different App ID's (perhaps you use one for production and one for development and didn't uninstall the app before switching?)

If not, can you please completely uninstall your app, then install the app, run it for ~30 seconds, and then send us a link to the logcat?

**Comment by ivanlyubimov** [comment] 2018-06-13 14:47
@Nightsd01 yes, I have deleted device manually from dashboard. Didn't think it would cause problem.

Anyways, If I uninstall app from device, it still appears on the dashboard. And app returns same error in logs. Here is [logfile](https://expirebox.com/download/4a59ddebf039698d7bc344437d697ccb.html)

**Comment by Nightsd01** [comment] 2018-06-13 18:20
@ivanlyubimov Yes, deleting a device from OneSignal will cause a problem when you keep trying to use that same device. 

This error means exactly the same thing. I would advise that you don't delete users from the dashboard from now on? Why are you deleting them in the first place? Perhaps there is a better way to accomplish what you are trying to do.

Also, I would recommend looking at [this troubleshooting section](https://documentation.onesignal.com/docs/troubleshooting-android#section-error-failed-to-resolve-com-android-support-customtabs-26-0-0-26-2-0-or-com-android-support-support-v4-26-0-0-26-2-0-) for that custom tabs issue.

**Comment by ivanlyubimov** [comment] 2018-06-13 18:30
@Nightsd01 After all, scenario where dashboard user deletes device is for testing purpose I supposed

I need to make sure that sdk indeed subscribes at the moment when user opens application
What would be right way to do that?

To clarify: after multiple sdk migrations, I want to ensure that thing works.
Devices I have were already subscribed to service, but sdk failed with #516 mentioned above. 
Now when we back to 1.3.4, due to nature of our app, we need to know that device is subscribed and user can accept notifications right after launch

**Comment by Nightsd01** [comment] 2018-06-13 23:52
We've made many bug fixes since 3.1.4.

In any case, the main issue you are facing is caused by the fact that you are deleting users so I'll be closing this issue, but we'll be happy to help you fix #516  and #515. 

When you update back to the latest version of our SDK, please post on either 515 or 516 depending on what issue you run into. Then in that git issue, please post your `app/build.gradle`, `android/build.gradle`, and `gradle-wrapper.properties`.

**Closed as completed by Nightsd01** 2018-06-13 23:52 UTC

**Comment by ivanlyubimov** [comment] 2018-06-14 01:54
@Nightsd01 yet you didn't address how could one test subscription correctly. Does it mean deleted device ids can no longer work with onesignal platfrom?

**Comment by jkasten2** [comment] 2018-06-19 22:12
@ivanlyubimov After the on_session error the SDK will automatically create a new player for your app even on the 3.1.4 SDK. We haven't seen any cases where this wasn't handled correct.

For the other issues you linked to we will follow up there

**Comment by nishkul** [comment] 2019-05-09 08:51
Above the same issue is have in android also with me and giving same bellow error as i deleted user from dashboard, not app is not uninstall 
OneSignalRestClient: POST RECEIVED JSON: {"errors":["not a valid device_type"]}
Failed last request. statusCode: 400
    response: null

**Comment by hugoh59** [comment] 2019-06-14 14:08
I'm also unable to register my android devices wether I use a real device or an emulator. No error message tho. I've followed all the setup instructions.
