### ISSUE TITLE
 Get initial route when App is opened from a notification

### ISSUE THREAD

**Issue by abelcha** [OneSignal/react-native-onesignal#1167] opened 2021-02-15 17:12 UTC
I'm using react-native and onesignal to handle notification.

If you press the notification when the app is in the background, i'll catch the 'opened' event, and redirect to the correct route (in the notification metadata)

But when the app is closed, the click on the notification just opens the app, without firing the 'opened' event.

How can i fetch the initial pressed notification metadata ?

Thanks

**Environment**
react-native@0.63.3
react-native-onesigna

**Steps to Reproduce Issue:**

* Close the app
* Send a notification
* Click on the notification
* The app opens, but can't redirect to the notification linked page

**Comment by rgomezp** [comment] 2021-02-17 21:34
Duplicate of #1125

**Comment by rgomezp** [comment] 2021-02-17 21:35
Thanks for reporting this. Please add any further details in the original issue and continue tracking there.

Thanks

**Closed as completed by rgomezp** 2021-02-17 21:34 UTC
