### ISSUE TITLE
Gonna add typescript support ?

### ISSUE THREAD

**Issue by mateusschenato** [OneSignal/react-native-onesignal#1071] opened 2020-10-27 16:49 UTC
Hi guys, when do you gonna add typescript support ?

Today everyone works with typescript, but you have not support for it :(

**Comment by rgomezp** [comment] 2020-10-27 18:07
Duplicate of #453

**Comment by rgomezp** [comment] 2020-10-27 18:08
We are planning on adding Typescript. Due to limited bandwidth we have not been able to make much progress. Thank you for your patience.

**Closed as completed by rgomezp** 2020-10-27 18:08 UTC
