### ISSUE TITLE
Example to send a data precise

### ISSUE THREAD

**Issue by DarkXelus** [OneSignal/react-native-onesignal#413] opened 2018-03-07 08:52 UTC
Hi,
Having no answer for #409  I raise here hoping someone can help me 

I can not send on a specific date yet I tried the following code without success. 
OneSignal.postNotification(contents, {}, token, 'Mon Mar 5 2018, 9:49:00 GMT-0100')

He send a notification now instead of the specified date and return a error

error: JSON value 'Mon Mar 5 2018, 9:49:00 GMT-0100' of NSString cannot be converted to NSDictionary
How to appear the badge?
Do you have an example to help me?

Thank

**Comment by Nightsd01** [comment] 2018-03-12 21:31
@DarkXelus please make sure to read the readme before posting a question like this....

The Readme shows that the last parameter of `postNotification()` is an ***object***, not a string.

You would want to send the notification like this:

```javascript
OneSignal.postNotification(contents, {}, token, {"send_after" : "Mon Mar 5 2018, 9:49:00 GMT-0100"});
```

Closing because this is a duplicate of #409. Apologies for not responding to you sooner.

**Closed as completed by Nightsd01** 2018-03-12 21:31 UTC
