### ISSUE TITLE
Android/setNotificationOpenedHandler sometimes not called

### ISSUE THREAD

**Issue by oferRounds** [OneSignal/react-native-onesignal#1166] opened 2021-02-15 11:45 UTC
**Description:**
On Android, `setNotificationOpenedHandler` is sometimes not called. Was not able to determine when it does get called, and when nnot

**Environment**

1. What version of the OneSignal React-Native SDK are you using?  `4.0.3`
1. How did you add the SDK to your project (eg. npm) `yarn`

Android environment: 
Using real device - Pixel 3

```
RNNKotlinVersion = "1.3.61"
RNNKotlinStdlib = "kotlin-stdlib-jdk8"
googlePlayServicesLocationVersion = "17.0.0"
googlePlayServicesIidVersion = "17.0.0"
googlePlayServicesAuthVersion = "19.0.0"
googlePlayServicesVersion = "17.0.0"
compileSdkVersion   = 28
targetSdkVersion    = 29
buildToolsVersion   = "29.0.2"
supportLibVersion   = "1.0.2"
mediaCompatVersion = "1.0.1"
supportV4Version = "1.0.0"
firebaseVersion = "17.2.2"
appCompatVersion = "1.1.0"
minSdkVersion = 21ndroid Pixel 3, 
```

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using yarn into your project
1. Attempt to receive a push notification when app is on background (not completely closed)
1. Get the notification
1. Tap the notification
1. `setNotificationOpenedHandler` sometimes get called and sometimes not

**Comment by oferRounds** [comment] 2021-02-15 12:47
Also, sometimes when the app launches regularly - without tapping the notification - this handler gets called with an old notification

**Comment by rgomezp** [comment] 2021-02-17 21:35
Duplicate of #1125

**Comment by rgomezp** [comment] 2021-02-17 21:35
Thanks for reporting this. Please add any further details in the original issue and continue tracking there

**Closed as completed by rgomezp** 2021-02-17 21:35 UTC

**Comment by oferRounds** [comment] 2021-02-18 08:04
@rgomezp the original post relates to iOS, this relates to Android

**Comment by oferRounds** [comment] 2021-02-18 08:04
Can you please reopen this?

**Comment by oferRounds** [comment] 2021-02-22 11:11
@rgomezp

**Comment by rgomezp** [comment] 2021-02-22 19:26
@oferRounds ,
The other issue is related to both platforms. I have updated the title to reflect this. Please track in that issue.
