### ISSUE TITLE
Launch URL not working on closed app(react native)

### ISSUE THREAD

**Issue by JJ810** [OneSignal/react-native-onesignal#1398] opened 2022-06-06 17:06 UTC
**Description:**

I'm sending push notifications with Launch URL.

When app is opened in background mode it opens the app correctly and launch url also works(it navigates to the expected screen).
But when app is completely closed the app only opens the app and doesn't navigate to the specific screen which is from the launch url.

**Environment**
react-native: 0.66.0
react-native-onesignal: 4.3.7

**Steps to Reproduce Issue:**

  1. Add the react-native-onesignal
  2. `cd ios && pod install`
  3. init onesignal sdk - `OneSignal.setAppId(Config.ONE_SIGNAL_KEY)` etc
  4. completely close the app.
  5. send push notification from onesignal dashboard(with launch url)
  6. press notification
 
This is a pretty urgent fix we need to fix on production. So please help as soon as possible! Thanks in advance!

**Comment by jkasten2** [comment] 2022-06-07 18:23
@JJ810 Thanks for reporting, this is a duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1016.

There is a work around you can noted below, however this would require you to eject from expo if you are using that:
https://github.com/facebook/react-native/issues/24429#issuecomment-1142075775

Another work around that doesn't require ejecting is to instead of using OneSignal's Launch URL is to set your URL in OneSignal's Additional Data on your notification. Then you can read this value in the `OneSignal.setNotificationOpenHandler` and send the URL to your deep linking library.

**Closed as completed** 2022-06-07 18:24 UTC
