### ISSUE TITLE
xcode15 - react native 0.72.4 [CP-User] [RNFB] Core Configuration error

### ISSUE THREAD

**Issue by sekizlipenguen** [OneSignal/react-native-onesignal#1569] opened 2023-09-27 15:30 UTC
```
Hi,

xcode:15
"react-native": "0.72.4",

Cycle inside *; building could produce unreliable results. This usually can be resolved by moving the shell script phase '[CP-User] [RNFB] Core Configuration' so that it runs before the build phase that depends on its outputs.
Cycle details:
→ Target '*': CodeSign /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app
○ Target '*' has process command with output '/Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app/Info.plist'
○ Target '*' has copy command from '/Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex' to '/Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app/PlugIns/OneSignalNotificationServiceExtension.appex'
○ That command depends on command in Target '*': script phase “[CP-User] [RNFB] Core Configuration”


Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app/_CodeSignature ->

command: P0:target-*-7955c8fbe0ab4408aecf35bb8f80ca637ceb6b36bcfc2fb90f69ac96de4975d6-:Debug:CodeSign /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app ->

CYCLE POINT ->

node: /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app/Info.plist/ ->

directoryTreeSignature: � ->

directoryContents: /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app/Info.plist ->

node: /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app/Info.plist ->

command: P0:target-*-7955c8fbe0ab4408aecf35bb8f80ca637ceb6b36bcfc2fb90f69ac96de4975d6-:Debug:ProcessInfoPlistFile /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app/Info.plist /Users/*/Desktop/projelerim/sekizlipenguen/cemal/*/ios/*/Info.plist ->

node: /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app/PlugIns/OneSignalNotificationServiceExtension.appex ->

command: P0:target-*-7955c8fbe0ab4408aecf35bb8f80ca637ceb6b36bcfc2fb90f69ac96de4975d6-:Debug:Copy /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app/PlugIns/OneSignalNotificationServiceExtension.appex /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex ->

node: <target-*-7955c8fbe0ab4408aecf35bb8f80ca637ceb6b36bcfc2fb90f69ac96de4975d6--fused-phase6--cp-user---rnfb--core-configuration> ->

command: P0:::Gate target-*-7955c8fbe0ab4408aecf35bb8f80ca637ceb6b36bcfc2fb90f69ac96de4975d6--fused-phase6--cp-user---rnfb--core-configuration ->

node: <execute-shell-script-7955c8fbe0ab4408aecf35bb8f80ca63f4b50de62cdc6822a0c2493a9898b9cf-target-*-7955c8fbe0ab4408aecf35bb8f80ca637ceb6b36bcfc2fb90f69ac96de4975d6-> ->

command: P2:target-*-7955c8fbe0ab4408aecf35bb8f80ca637ceb6b36bcfc2fb90f69ac96de4975d6-:Debug:PhaseScriptExecution [CP-User] [RNFB] Core Configuration /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Intermediates.noindex/*.build/Debug-iphonesimulator/*.build/Script-FB2FCEB9CBDD984D9867BDF5.sh ->

  node: /Users/*/Library/Developer/Xcode/DerivedData/*-ghsfobqzgrsysccszfkqabkxxgcy/Build/Products/Debug-iphonesimulator/*.app/Info.plist/


podfile


# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
use_frameworks! :linkage => :static
$RNFirebaseAnalyticsWithoutAdIdSupport=true

target 'napios' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    #:hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :hermes_enabled => false,
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    #:flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'napiosTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(installer,config[:reactNativePath], :mac_catalyst_enabled => false )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.build_configurations.each do |config|
       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
     end
  end

  # React Native Maps dependencies
  # The following line is only needed if building on an Apple silicon Mac without rosetta.
  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.12.3', '< 4.0'
end



```

**Comment by OguzEkinci** [comment] 2023-09-27 22:11
same issue here, when i added the widget extension on app

**Comment by OguzEkinci** [comment] 2023-09-27 22:22
omg! i found something, do this:

In fact, you only need to pay attention to Xcode's prompt This usually can be resolved by moving the target's Headers build phase before Compile Sources, and then you can do it.

**Comment by AhmedHF** [comment] 2023-09-27 22:34
> omg! i found something, do this:
> 
> In fact, you only need to pay attention to Xcode's prompt This usually can be resolved by moving the target's Headers build phase before Compile Sources, and then you can do it.

how to 
solve this issue?

**Comment by AhmedHF** [comment] 2023-09-27 22:37
target's Headers not moving why?

**Comment by OguzEkinci** [comment] 2023-09-28 00:49
move "Embed Foundation extension" before "Compile sources".
whenever your errors, mine is "Embed Foundation extension" because when i create widgetextension, i face this issue

**Comment by sheunglys** [comment] 2023-09-28 02:31
same issue here, no idea where can i move 
[CP-User] [RNFB] Core Configuration

**Comment by vishaldaher** [comment] 2023-09-28 05:28
> move "Embed Foundation extension" before "Compile sources". whenever your errors, mine is "Embed Foundation extension" because when i create widgetextension, i face this issue

This resolved my issue Thanks @OguzEkinci

**Comment by AhmedHF** [comment] 2023-09-28 06:46
> move "Embed Foundation extension" before "Compile sources". whenever your errors, mine is "Embed Foundation extension" because when i create widgetextension, i face this issue

Thanks a lot @OguzEkinci

**Comment by whyamsx** [comment] 2023-09-28 06:57
> move "Embed Foundation extension" before "Compile sources". whenever your errors, mine is "Embed Foundation extension" because when i create widgetextension, i face this issue

Thank you! This solved the problem for me too!

**Comment by sekizlipenguen** [comment] 2023-09-28 07:27
I observed that this problem started with xcode 15. xcode 14.3.1 works without any problems.

Also, for xcode15, the cause of the problem starts after adding "OneSignalNotificationServiceExtension".

**Comment by sekizlipenguen** [comment] 2023-09-28 07:30
> move "Embed Foundation extension" before "Compile sources". whenever your errors, mine is "Embed Foundation extension" because when i create widgetextension, i face this issue

Hi,
How can I do this via xcode? I didn't fully understand. Any chance of taking a screenshot?

**Comment by sekizlipenguen** [comment] 2023-09-28 07:40
![Screenshot 2023-09-28 at 10 39 26](https://github.com/OneSignal/react-native-onesignal/assets/36849861/70daa9ae-a142-497f-87dc-718130542abb)

I solved this problem by ticking this. "copy only when installing"

**Comment by maderesponsively** [comment] 2023-10-06 12:33
> ![Screenshot 2023-09-28 at 10 39 26](https://user-images.githubusercontent.com/36849861/271207976-70daa9ae-a142-497f-87dc-718130542abb.png)
> 
> I solved this problem by ticking this. "copy only when installing"

I can confirm that this worked for me.

**Comment by DiorAbjalilov** [comment] 2023-10-30 11:01
> ![Screenshot 2023-09-28 at 10 39 26](https://user-images.githubusercontent.com/36849861/271207976-70daa9ae-a142-497f-87dc-718130542abb.png)
> 
> I solved this problem by ticking this. "copy only when installing"

Tahnks. worked for me

**Comment by wuchangming** [comment] 2023-11-19 14:07
> ![Screenshot 2023-09-28 at 10 39 26](https://user-images.githubusercontent.com/36849861/271207976-70daa9ae-a142-497f-87dc-718130542abb.png)
> 
> I solved this problem by ticking this. "copy only when installing"

However, if checked "copy only when installing", the widget **cannot** be displayed on the simulator.

**Comment by wuchangming** [comment] 2023-11-19 14:08
![image](https://github.com/OneSignal/react-native-onesignal/assets/5039340/dac77bf7-f55c-4ea6-929f-73cc1781cbee)
![image](https://github.com/OneSignal/react-native-onesignal/assets/5039340/5e781c38-4cae-43e3-942c-293168bcf140)

I fixed it by adjusting the order.

**Comment by usamaabutt** [comment] 2024-02-20 09:40
> ![Screenshot 2023-09-28 at 10 39 26](https://private-user-images.githubusercontent.com/36849861/271207976-70daa9ae-a142-497f-87dc-718130542abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjE5OTcsIm5iZiI6MTcwODQyMTY5NywicGF0aCI6Ii8zNjg0OTg2MS8yNzEyMDc5NzYtNzBkYWE5YWUtYTE0Mi00OTdmLTg3ZGMtNzE4MTMwNTQyYWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA5MzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZTkwOTA5OTcyNzg0YjliNmI1MTRhMzRlZjNhM2NiZDllYzA4YTg5NDAwNjUyMjJhMDAyNzRjYzY2YjYyMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vqhCRhuzNY3jcKlcL_0t5j4CnGw9Mi5hZJFwSaeoc0c)
> 
> I solved this problem by ticking this. "copy only when installing"


react-native: v0.68.6
react-native-onesignal: v4.4.1
I also confirmed this works for me. Thank you very much!!!

<img width="1203" alt="Screenshot 2024-02-20 at 2 48 23 PM" src="https://github.com/OneSignal/react-native-onesignal/assets/44516486/022541d8-0314-4036-a010-b71a8675dbef">

**Comment by usamaabutt** [comment] 2024-02-20 10:16
> move "Embed Foundation extension" before "Compile sources". whenever your errors, mine is "Embed Foundation extension" because when i create widgetextension, i face this issue

I confirmed this fixed my build archived error. Thanks a lot!

**Comment by ebnersilva** [comment] 2024-02-23 20:03
@sekizlipenguen thanks man, your solution works for me 🙏🏻

**Comment by RayanAbid** [comment] 2024-03-17 18:38
> move "Embed Foundation extension" before "Compile sources". whenever your errors, mine is "Embed Foundation extension" because when i create widgetextension, i face this issue

Worked for me as well Xcode 15.3 "react-native": "0.73.5", Thanks @OguzEkinci

**Comment by nameisjayant** [comment] 2024-05-17 06:21
In my case, I move my **_Copy Bundle Resource_** above to **_Compile Source_**.

<img width="537" alt="Screenshot 2024-05-17 at 11 51 44 AM" src="https://github.com/OneSignal/react-native-onesignal/assets/38830570/06e274d2-dd05-4ff3-bbd1-299434294d64">

**Comment by tnson1307** [comment] 2024-05-25 13:28
> ![Screenshot 2023-09-28 at 10 39 26](https://private-user-images.githubusercontent.com/36849861/271207976-70daa9ae-a142-497f-87dc-718130542abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDM3MDIsIm5iZiI6MTcxNjY0MzQwMiwicGF0aCI6Ii8zNjg0OTg2MS8yNzEyMDc5NzYtNzBkYWE5YWUtYTE0Mi00OTdmLTg3ZGMtNzE4MTMwNTQyYWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzMjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MWE2MzU5YTc2ZWJhZTdmN2VhYTIyNjQ3ZmJlYmExZjZiN2RjMjRiMjI1ZmY3MDgzMWI5MjExMjRhZWNiMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulMnXgoAxRJGkZK8QRO2HZBrOBGk58fr4fciMHYEWyc)
> 
> I solved this problem by ticking this. "copy only when installing"

yes it's work for me

**Comment by charithAmila** [comment] 2024-08-01 00:52
> > ![Screenshot 2023-09-28 at 10 39 26](https://user-images.githubusercontent.com/36849861/271207976-70daa9ae-a142-497f-87dc-718130542abb.png)
> > I solved this problem by ticking this. "copy only when installing"
> 
> However, if checked "copy only when installing", the widget **cannot** be displayed on the simulator.

Try this one : https://github.com/OneSignal/react-native-onesignal/issues/1569#issuecomment-1817866408

**Comment by vanhai989** [comment] 2024-09-05 15:27
I can confirm to resolve this issue we move the [CP-User] [RNFB] Core Configuration to the end of Build Phases. I hope it can help you

**Comment by musabjaved10** [comment] 2024-11-18 10:21
> ![Screenshot 2023-09-28 at 10 39 26](https://private-user-images.githubusercontent.com/36849861/271207976-70daa9ae-a142-497f-87dc-718130542abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjQ3MzMsIm5iZiI6MTczMTkyNDQzMywicGF0aCI6Ii8zNjg0OTg2MS8yNzEyMDc5NzYtNzBkYWE5YWUtYTE0Mi00OTdmLTg3ZGMtNzE4MTMwNTQyYWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDEwMDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTkzNDExOWUzMTYxM2VjMjhjYWQ3YTZmZjI3M2JhNzRlZjM0YWE1Mjk0ZDFmNGY0NGUyMDA0ZjJkMGNkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sHhag0rPf1q23GbTeBcJ6BBw4YT33Q4gtmw8lOogUNg)
> 
> I solved this problem by ticking this. "copy only when installing"

Fixed ! Thanks

**Closed as completed** 2024-12-07 00:27 UTC

**Comment by sarowerj** [comment] 2025-02-12 08:28
> ![Screenshot 2023-09-28 at 10 39 26](https://github.com/OneSignal/react-native-onesignal/assets/36849861/70daa9ae-a142-497f-87dc-718130542abb)
> 
> I solved this problem by ticking this. "copy only when installing"

this solution worked for me.

**Comment by dhanabalan2002** [comment] 2025-03-31 10:58
> omg! i found something, do this:
> 
> In fact, you only need to pay attention to Xcode's prompt This usually can be resolved by moving the target's Headers build phase before Compile Sources, and then you can do it.

this solution worked for me.

Thank you so much @OguzEkinci
