### ISSUE TITLE
Track location not work properly

### ISSUE THREAD

**Issue by luizstacio** [OneSignal/react-native-onesignal#1032] opened 2020-08-12 15:53 UTC
**Description:**

The location is not getting track. Our app already asks for location permissions and it's able to get the user location. But the OneSignal didn't track all users. Some of them didn't send the location at all.

All our users have location permission enable, without location permission the app didn't work...

I had the same issue before to try to solve it I did the following solution. Calling the method `promptLocation` even when the user already has the location enable.

This resolves part of the issue because most users start to track but not all.
I had tried to `setTags` with latitude and longitude manually too, but it didn't work and I didn't find other ways to set this location manually this would help me to solve this problem.

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK and `react-native-permissions` using npm into your project
1. Initialize OneSignal with init on App.tsx
1. Request permissions using `react-native-permissions`
1. OneSignal should start show location but do not.

**Comment by rgomezp** [comment] 2020-08-19 23:14
Howdy,
Can you please include a log from the device with logLevel set to VERBOSE?

This seems like it is possibly a duplicate of this issue: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/533

**Comment by luizstacio** [comment] 2020-08-20 00:16
Hi @rgomezp I think is the other way around... Because now it's not tracking... I call the `setLocationShared(true)` right after initialization and it not works.

I will provide logs

**Comment by rgomezp** [comment] 2020-08-25 22:37
Howdy @luizstacio ,
I was just checking in to see if you had gotten those logs. If you have resolved, can we close this issue?

Cheers

**Comment by rgomezp** [comment] 2020-10-02 22:05
Closing due to no response

**Closed as completed by rgomezp** 2020-10-02 22:05 UTC
Labels: Help Wanted, Need More Information
