### ISSUE TITLE
OneSignal.init sets the subscription to true

### ISSUE THREAD

**Issue by Stekmo** [OneSignal/react-native-onesignal#545] opened 2018-06-06 07:24 UTC
**Description:**

In my root component I'm calling OneSignal.init to initialize OneSignal. In another component I'm allowing the user to disable or enable push, by using the OneSignal.setSubscription(bool). After disabling push by using OneSignal.setSubscription(false), I don't recieve push when the app is in the background or hard closed, just as intended. However once I open the app, after it being hard closed, it has set the subscription to true, meaning that the app once again recieves push notifications. I can't think of any other logical explanation than it being somehow related to OneSignal being initialized again. 

**Environment**

Using react-native-onesignal 3.2.3

**Steps to Reproduce Issue:**

1. Initialize OneSignal
2. Use OneSignal.setSubscription(false)
3. Verify that the subscription is set to false with OneSignal.getPermissionSubscriptionState
4. Hard close the app
5. Open it again
6. Check the permissions state again with OneSignal.getPermissionSubscriptionState

**Anything else:**
I couldn't reproduce this on my iOS simulator, but on both my iOS phone and Android phone this occured.

**Comment by Nightsd01** [comment] 2018-06-08 00:35
@Stekmo This setting gets persisted/saved, so it likely means that, somewhere, you are setting `setSubscription(true)` somewhere in your app without noticing it.

If you installed `react-native-onesignal` with npm, I would recommend opening your Xcode project, and edit `RCTOneSignalEventEmitter.m` in the react-native-onesignal library. Place a breakpoint on the `setSubscription` method, or an NSLog statement, and make sure it never gets called.

**Comment by Nightsd01** [comment] 2018-06-09 01:58
Assuming that you had a misplaced `setSubscription` call somewhere in your project so I’m closing the issue, please reply if you’re still having this problem and I’ll be happy to reopen and investigate.

**Comment by focalsolution** [comment] 2020-01-12 07:50
I am facing this similar problem and can reproduce with the Example that comes with the package - RNOneSignal. Not quiet sure if anyone found a solution.

**Comment by rgomezp** [comment] 2020-01-13 20:02
@focalsolution ,
Can you confirm you are seeing this on both iOS and Android?

**Comment by focalsolution** [comment] 2020-01-14 04:09
@rgomezp I have not tested on Android yet. If I got a chance, I will let you know.

A bit more info, I found this problem on react-native-onesignal 3.6.2. However, it seem to work correctly when I roll back to 3.5.0.

Hope this could help.

**Comment by rgomezp** [comment] 2020-01-15 21:21
Thanks for the details @focalsolution

**Comment by rgomezp** [comment] 2020-01-27 23:37
Closing due to no response

**Closed as completed by rgomezp** 2020-01-27 23:37 UTC
Labels: Need More Information
