### ISSUE TITLE
Cannot fire addEventListener 'opened' / setNotificationOpenedHandler not working

### ISSUE THREAD

**Issue by rukmanary** [OneSignal/react-native-onesignal#1125] opened 2020-12-17 08:01 UTC
**Into**
I already check similar issues but it doesn't give me a clear answer.

**Description:**
Actually, I am having 2 problems, I am not sure about event 'received' because my first problem is I can't get any notification in foreground. But let skip this one... So, I am concern in event 'opened'. When the app running in background, I send push notification and receive it, so then I tap the notification. The function in addEventListener is not called. It does takes me back to the app but it does nothing. It works really fine in Android. I call this on ComponentDidMount

```
 componentDidMount() {
    this._setupOneSignal();
  }
  
componentWillUnmount() {
    this._unMountOneSignal();
  }

 _setupOneSignal = () => {
    OneSignal.init(ONESIGNAL_APP_ID, { kOSSettingsKeyAutoPrompt: true });
    OneSignal.inFocusDisplaying(2);
    OneSignal.enableSound(true);
    OneSignal.enableVibrate(true);
    OneSignal.addEventListener('received', this._onReceived);
    OneSignal.addEventListener('opened', this._onOpened);
    OneSignal.addEventListener('ids', this._onIds);
    OneSignal.addEventListener(
      'inAppMessageClicked',
      this._onInAppMessageClicked,
    );
    OneSignal.setLogLevel(6, 0);

    OneSignal.getPermissionSubscriptionState(
      ({ userSubscriptionEnabled: oneSignalSubscription }) => {
        this.mainSet({ oneSignalSubscription });
      },
    );

    DeviceInfo.getVersion().then(version => {
      OneSignal.sendTag('version', version);
    });
    DeviceInfo.getBuildNumber().then(build => {
      OneSignal.sendTag('build', build);
    });
  };

_unMountOneSignal = () => {
    OneSignal.removeEventListener('received', this._onReceived);
    OneSignal.removeEventListener('opened', this._onOpened);
    OneSignal.removeEventListener('ids', this._onIds);
  };

  _onReceived(notification) {
    OneSignal.enableSound(true);
    console.log('Notification received: ', notification);
  }

  _onOpened = ({ notification: { payload } }) => {
    console.log(JSON.stringify(payload));
    console.log('hello world');
  };

  _onIds(device) {
    // console.log('device: ', device);
  }
```

when I click the notification, it doesn't even print that `hello world`

**Environment**

1. react: 16.9.0
1. react-native: 0.61.1
1. react-native-onesignal: 3.6.4
1. @react-native-community/push-notification-ios: 1.7.3

My Podfile.lock:

* react-native-onesignal (3.9.2):
  * OneSignal (= 2.15.4)
  * React (< 1.0.0, >= 0.13.0)

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using npm into your project
1. Initialize the SDK in the iOS AppDelegate
1. Attempt to receive a push notification
1. Click on notification
1. Direct to App, but does nothing

**Comment by ralvesfull** [comment] 2020-12-22 19:48
I've the same problem

**Comment by rgomezp** [comment] 2021-01-13 20:25
Howdy,
Thanks for your patience. The `addEventListener` functionality was removed in the latest major release anyway. Can you please migrate to the new version?

**Comment by joelrorseth** [comment] 2021-01-21 02:08
I am experiencing the exact same issue, but using the new `setNotificationOpenedHandler` with `react-native-onesignal 4.0.3`. I cannot, for the life of me, get this handler to fire. I have tried putting the declaration in my index.js / App.js constructor and componentDidMount, with no luck. The handler is being set, as far as I can tell. Using setLogLevel(0,6), the only interesting log messages are "Notification opened handler set successfully" and "provision not found".

I am testing all of this using the iOS 14.3 simulator, could that perhaps be an issue? I am sending notifications to the simulator using `xcrun simctl push booted com.company.app-name payload.json`

**Comment by GuilhermeGuerra4** [comment] 2021-01-23 13:14
> I am experiencing the exact same issue, but using the new `setNotificationOpenedHandler` with `react-native-onesignal 4.0.3`. I cannot, for the life of me, get this handler to fire. I have tried putting the declaration in my index.js / App.js constructor and componentDidMount, with no luck. The handler is being set, as far as I can tell. Using setLogLevel(0,6), the only interesting log messages are "Notification opened handler set successfully" and "provision not found".
> 
> I am testing all of this using the iOS 14.3 simulator, could that perhaps be an issue? I am sending notifications to the simulator using `xcrun simctl push booted com.company.app-name payload.json`

same issue in android, i'm migrating back to 3.9.2

**Comment by rgomezp** [comment] 2021-01-27 22:03
@joelrorseth ,
Yes. That is the issue. Unfortunately notifications aren't fully supported on the simulator, a general limitation of iOS development. I suspect testing on a real device will resolve the issue for you.

@GuilhermeGuerra4 ,
We haven't been able to reproduce this issue. If you are anyone else could include a link to an example (or blank) project that reproduces the issue that would be very helpful.

Cheers

**Comment by rgomezp** [comment] 2021-02-17 21:37
It sounds like several people are encountering this issue as noted by the above closed issues referencing this one.

This sounds like a possible bug.

We haven't been able to reproduce so if anyone has a project that they could share we could inspect, please let us know.

If you don't want to share the project publicly please reach out to our support team at OneSignal.com where you can share with us directly.

Cheers

**Comment by rgomezp** [comment] 2021-02-17 21:39
It also looks like this has been reported on both platforms, meaning most likely that this is an issue/bug at the React Native SDK level.

Please see the [above comment](https://github.com/OneSignal/react-native-onesignal/issues/1125#issuecomment-780871157) regarding providing a reproducing project. 

Cheers

**Comment by rgomezp** [comment] 2021-04-07 22:08
Is anyone still facing this issue?

**Comment by rukmanary** [comment] 2021-04-08 16:41
I am so sorry to not follow up this issue again. I have been occupied in migrating firebase to version 6 and other stuff. I need to migrate because every time I click on push notification with v5, the app will crash. It is an issue in react native firebase for iOS 14. And somehow it solved this issue too. I am not sure how is the connection between firebase and onesignal. But, since I updated my firebase to version 6, I am not facing this anymore.

But, once again, I am not sure this is the solution.

**Comment by vt978** [comment] 2021-04-09 05:54
In ios, setNotificationOpenedHandler was working fine whether the app is opened or closed. 

But in android, clicking notification while app is closed doesnt fire the app. When the app is in focus, click on notification will result in either no respond or the action firing several minutes later when i leave the app open. In ios there wasnt any delay or problem with it, but only happen in android.

Not sure the cause of the problem.

**Comment by rgomezp** [comment] 2021-04-22 16:50
Possible duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/749

**Comment by nan-li** [comment] 2022-02-08 17:26
Hi @vt978, sorry for the delayed followup, are you still experiencing this issue?

**Comment by SaliniG** [comment] 2022-02-15 12:36
still facing this issue in android.. Please help me

**Comment by michaelcsilva** [comment] 2022-02-15 18:02
i see this in iOS as well, I am using 
    "react-native-onesignal": "^3.9.4",
    "react-native": "0.64.2",

it seem to work initially (i.e. on fresh install of the app) but stops working after a day or so of normal use (e.g. background/foregrounding the app, etc.).

**Comment by nan-li** [comment] 2022-02-22 19:24
Hi @SaliniG, @michaelcsilva,
We are still not able to reproduce this on our end, 
Please see the [above comment](https://github.com/OneSignal/react-native-onesignal/issues/1125#issuecomment-780871157) regarding providing a reproducing project. 

Update: This may also be related to the type of device, can you share also what device you are experiencing this on?

**Comment by rgomezp** [comment] 2022-06-03 21:55
Closing due to inactivity

**Closed as completed by rgomezp** 2022-06-03 21:55 UTC
Labels: Help Wanted, iOS, Possible Bug, Android, Need More Information
