### ISSUE TITLE
iOS - action button still not showing on iOS 12.x

### ISSUE THREAD

**Issue by gabrielgc** [OneSignal/react-native-onesignal#774] opened 2019-06-12 09:57 UTC
**Description:**

On iOS v12.x the action buttons just show if the push notification has an image attached. Once I send at least one notification with image, the subsequent notification will show the buttons even without an image.
I know that the [closed issue 690 is very similar to this](https://github.com/geektimecoil/react-native-onesignal/issues/690), but it was closed mentioning that this bug just happens on while running on the local environment, but I got my app in production and the bug still happening on the apple store version. 

Is there any solution for this that wasn't mentioned on the other issue discussion?

**Environment**
dev:
macOS Mojave version 10.14.4
Xcode version 10.2
"react-native-onesignal": "^3.2.12",

production
iPhone X - iOS 12.2

**Steps to Reproduce Issue:**

1. Create a fresh react native app
2. Install react native onesignal
3. Run the react native in iOS v12.0.1
4. Send a push notification with actions buttons

**Anything else:**
Raw push notification object (containing buttons) 
`{  
   "att":{  
      "id":"1"
   },
   "custom":{  
      "a":{  
         "message_type":"CustomMessage",
         "id":"4b7cbde2-555b-44b0-857e-9cd442894c15"
      },
      "i":"4bb26ad3-d358-4b87-a8b2-21a96c8ca64c"
   },
   "buttons":[  
      {  
         "i":"OnYes",
         "n":"Yes"
      },
      {  
         "i":"OnNo",
         "n":"No"
      }
   ],
   "aps":{  
      "content-available":1,
      "alert":{  
         "title":"Health Check",
         "body":"Message with action buttons"
      },
      "mutable-content":1,
      "sound":"default"
   }
}`

**Comment by rgomezp** [comment] 2019-06-17 23:03
Hello @gabrielgc thanks for your message.
Unfortunately, I don't know of a solution other than waiting for Apple to fix this. Thanks for reporting seeing it in production. I will leave open so we can track it here.

**Comment by rgomezp** [comment] 2019-11-13 00:37
This is a duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/issues/430

**Closed as completed by rgomezp** 2019-11-13 00:37 UTC
Labels: iOS, Not OneSignal

**Comment by gabrielgc** [comment] 2020-01-31 10:24
Fixed on version 3.6.3
