### ISSUE TITLE
PushToken is always null just in iOS

### ISSUE THREAD

**Issue by gabrielCodeSolutions** [OneSignal/react-native-onesignal#927] opened 2019-12-27 17:24 UTC
**Description:**

My push token is always null on all versions of iOS, not just iOS 13 like is happening with other people.
This issue started to happen out of the blue.  In Android is working correctly.
I was using the 3.2.7 version but i tried to use the newest version (3.6.1) to check if this was the problem but, it was not the problem. Please, i need help! 

![Captura de Tela 2019-12-27 às 14 22 24](https://user-images.githubusercontent.com/20730701/71526172-55fba180-28b4-11ea-9026-91c16a1f4108.png)

**Environment**

I'm using the version 3.6.1 of react-native-onesignal
I added  the react-native-onesignal using npm and linking manually

**Steps to Reproduce Issue:**

1. Install  and do the correct the last version of the One Signal SDK 3.6.1
2. Do a console.log in the one signal data using the method getPermissionSubscriptionState

**Anything else:**

There isn't any crash log because the app does not crash.
It just appears a log in the Xcode described in the image below: 
![Captura de Tela 2019-12-27 às 14 20 35](https://user-images.githubusercontent.com/20730701/71526130-12089c80-28b4-11ea-8d9c-9fb01154a5c6.png)

I searched and  all the issues (https://github.com/OneSignal/react-native-onesignal/issues/910, https://github.com/OneSignal/react-native-onesignal/issues/847) but still not working.

**Comment by rgomezp** [comment] 2020-01-02 21:11
What does the OneSignal dashboard say (for that device)?

Edit:
Duplicate of #910 , have you tried the suggestion in that thread about removing the `configure `function?

**Comment by rgomezp** [comment] 2020-01-28 00:02
Closing due to no response

**Closed as completed by rgomezp** 2020-01-28 00:02 UTC
Labels: Help Wanted
