### ISSUE TITLE
Unable to build on real device

### ISSUE THREAD

**Issue by thormengkheang** [OneSignal/react-native-onesignal#1293] opened 2021-09-29 05:50 UTC
**Description:**

Unable to run my app on real device but run fine on simulator.

**Environment**

"react-native": "0.63.4"
"react-native-onesignal": "^4.3.1",

**Steps to Reproduce Issue:**

1. Connect real device
2. Run build

**Error Log:**

ld: building for iOS, but linking in dylib file (/Users/kheang/Library/Developer/Xcode/DerivedData/elevator-fqjpztlxeridfdgsnznclijzmwny/Build/Products/Release-iphoneos/OneSignal.framework/OneSignal) built for Mac Catalyst, file '/Users/kheang/Library/Developer/Xcode/DerivedData/elevator-fqjpztlxeridfdgsnznclijzmwny/Build/Products/Release-iphoneos/OneSignal.framework/OneSignal' for architecture arm64

**Comment by nan-li** [comment] 2021-09-29 22:26
Hi @thormengkheang, what version of cocoapods are you using? 
Your error sounds like a cocoapods bug, make sure you're using latest cocoapods version or at least 1.10+

Otherwise, try these things:
- deintegrating the pod and re-installing
- clearing the derived data folder and cache.

Also please provide your Podfile if still erroring.

**Comment by thormengkheang** [comment] 2021-09-30 01:53
I'm using cocoapods version 1.10.1 but I downgrade react-native-onesigal to version 4.1.1 I'm able to build again.

**Comment by PaulOskarSoe** [comment] 2021-12-13 09:37
I am having the same issue, all the versions from 4.1.1 are failing on ```react-native: 0.63.4```.  For me code gets compiled, but once code is ran on device I am getting a black screen and error in xcode. 

![image](https://user-images.githubusercontent.com/35954675/145787629-55166226-a99c-4682-b667-1366ddd53d0e.png)

**Comment by rgomezp** [comment] 2021-12-16 19:48
Howdy,
Are y'all able to update to RN 64? To try it out?

Possible duplicate of #1260

**Comment by rgomezp** [comment] 2022-06-03 22:03
Closing due to inactivity

**Closed as completed by rgomezp** 2022-06-03 22:03 UTC
Labels: Compatibility Issue
