### ISSUE TITLE
Click on push notification should navigate to the desired screen

### ISSUE THREAD

**Issue by mukeshkamboj** [OneSignal/react-native-onesignal#336] opened 2017-10-13 07:33 UTC
I have made an application using the react native and onesignal (thanks for the effort that put in to build this wonderful library).

I am able to receive the notifications from onesignal, but if app is not running and push notification is received then clicking on the push notification doesn't navigate to the desired screen. Please suggest me a solution for this problem. How this can be solved?

I am using the [route-flux ](https://github.com/aksonov/react-native-router-flux) for routing in my app.

This is not an issue when app is running and notification is received.

**Comment by jordanmkoncz** [comment] 2017-11-02 06:10
Just a heads up that I've posted a pretty lengthy comment at https://github.com/geektimecoil/react-native-onesignal/issues/332#issuecomment-341326624 discussing this problem.

**Comment by Nightsd01** [comment] 2018-02-27 21:14
Closed as duplicate of #332. Please feel free to respond if you are still encountering this issue @mukeshkamboj

**Closed as completed by Nightsd01** 2018-02-27 21:14 UTC
