### ISSUE TITLE
[Bug]:  App crashes on initialization

### ISSUE THREAD

**Issue by allysonfield** [OneSignal/react-native-onesignal#1630] opened 2024-01-11 20:48 UTC
### What happened?

On run app crashes

### Steps to reproduce?

```Markdown
1. Install the lib
2. Run
```

### What did you expect to happen?

yarn android

### React Native OneSignal SDK version

5.0.4

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
FATAL EXCEPTION: pool-10-thread-1

Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

FATAL EXCEPTION: pool-10-thread-1
Process: com.br.dev.cana, PID: 6448
java.lang.IllegalArgumentException: com.br.dev.cana: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:671)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:658)
	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:285)
	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:158)
	at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:185)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:103)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment] 2024-01-17 18:51
Hi @allysonfield thanks for reaching out. I believe this may be due to a work-runtime dependency issue that was recently fixed in our [latest Android SDK release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.1). We are working on getting an update out for wrapper SDKs ASAP.

**Comment by jennantilla** [comment] 2024-02-02 23:56
@allysonfield apologies--it looks like I misread/misdiagnosed this issue as I actually don't see any relation to OneSignal or work-runtime. If you are still having issues please @ mention me with full reproduction steps and I'll be happy to investigate further!

**Closed as completed by jennantilla** 2024-02-02 23:56 UTC

**Comment by allysonfield** [comment] 2024-02-03 14:01
I only created a new project and worked! The problem was caused by config imcomplete on RN upgrade
