### ISSUE TITLE
Package react-native-onesignal has been ignored because it contains invalid configuration

### ISSUE THREAD

**Issue by DevAelius** [OneSignal/react-native-onesignal#795] opened 2019-07-08 10:12 UTC
actually i am trying to configure React Native one signal in react native application for the push notification purpose

Environment Setup 1 : react-native version : 0.60 2 : npm version 10.5

for that i follow below official documentation of React native one signal

https://documentation.onesignal.com/docs/react-native-sdk-setup

step 1 : npm install -g react-native-cli, status : done

step 2 : react-native init OneSignalDemo status : done (before linking project i run project successfully with below command ) { 1 command : react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

2 command : react-native run-android }

step 3 : react-native link react-native-onesignal

Linking oneSignal with my App (As per official documentation)
          status : fail
Problem : While linking my library with above command i got a below error in my terminal

Package react-native-onesignal has been ignored because it contains invalid configuration. Reason: Unknown option dependency.platforms.ios.sourceDir with value ""./ios"" was found. This is either a typing error or a user mistake

solution wich i tryed

i make new react native project with version 0.58.0

as follow instuction as per https://documentation.onesignal.com/docs/react-native-sdk-setup

i got same error

Thank in advance !

**Comment by rgomezp** [comment] 2019-07-08 23:14
Duplicate of #792

**Closed as completed by rgomezp** 2019-07-08 23:14 UTC

**Comment by sirajalam049** [comment] 2019-07-19 13:50
Make this change in your package.JSON

"react-native-onesignal": "git+ssh://git@github.com/geektimecoil/react-native-onesignal.git",

**Comment by aakashpunasiya21** [comment] 2022-03-09 10:15
I am use react-native-web i am using custom font and when i run command "npx react-native link" it gives warn Package expo-modules-core has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios" must be of type object.

please provide good solution.
