### ISSUE TITLE
error: unreported exception JSONException; must be caught or declared to be thrown                callback.invoke(RNUtils.jsonToWritableMap(outcomeEvent.toJSONObject()));

### ISSUE THREAD

**Issue by andrealencar** [OneSignal/react-native-onesignal#1004] opened 2020-06-15 04:40 UTC
I am getting the following error when trying to run the application:

*Command:
 npx react-native run-android  Error compiling:

 *my settings:
    "react": "16.9.0",
    "react-native": "0.60.5",
    "react-native-onesignal": "^3.8.0",

*Error:

react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:489: error: unreported exception JSONException; must be caught or declared to be thrown
               callback.invoke(RNUtils.jsonToWritableMap(outcomeEvent.toJSONObject()));
                                                                                  ^
/Users/MacBook/Projects/React_Native/HeroApp/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:502: error: unreported exception JSONException; must be caught or declared to be thrown
               callback.invoke(RNUtils.jsonToWritableMap(outcomeEvent.toJSONObject()));

**Comment by thongncvn** [comment] 2020-06-15 07:27
May this be related? https://github.com/OneSignal/react-native-onesignal/issues/1003

**Comment by mikechoch** [comment] 2020-06-15 14:36
Duplicate of #1003

**Closed as completed by mikechoch** 2020-06-15 14:36 UTC
