### ISSUE TITLE
Crashed when receive notification Android 6

### ISSUE THREAD

**Issue by vinpro24** [OneSignal/react-native-onesignal#1011] opened 2020-06-27 12:03 UTC
App crashed in Android  6 when receive notification. Working fine on iOS and Android 10. Had checked out similar cases but couldn't find solution for Android.

Environment
"react-native": "0.63.0-rc.1",
"react-native-onesignal": "^3.8.1"

**Comment by rgomezp** [comment] 2020-06-29 17:47
Duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/930

If you believe otherwise, please open a new issue and make sure to follow our issue template so we can better assist you.

**Closed as completed by rgomezp** 2020-06-29 17:47 UTC
