### ISSUE TITLE
[ReactNative]: Disabled setWebContentsDebuggingEnabled react-native-oneSignal 

### ISSUE THREAD

**Issue by ocharlespereira** [OneSignal/react-native-onesignal#1410] opened 2022-07-19 13:09 UTC
### How can we help?

How disabled **_setWebContentsDebuggingEnabled_** debug mode in react-native-onesignal? I want to pass this parameter to false.

```
 // Allow Chrome Remote Debugging if OneSignal.LOG_LEVEL.DEBUG or higher
    private static void enableWebViewRemoteDebugging() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT &&
                OneSignal.atLogLevel(OneSignal.LOG_LEVEL.DEBUG)) {
            WebView.setWebContentsDebuggingEnabled(true);
        }
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment] 2022-07-19 18:21
Duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1409

**Closed as completed by jkasten2** 2022-07-19 18:21 UTC
