### ISSUE TITLE
[Android] Handle links when `meta-data android:name="com.onesignal.NotificationOpened.DEFAULT` is DISABLE and the app is closed

### ISSUE THREAD

**Issue by BokiGaja** [OneSignal/react-native-onesignal#1214] opened 2021-05-10 08:50 UTC
Hi guys, I had some problem when I wanted to handle deep links in the `launchUrl` so I don't get `Open with` prompt screen.

**Description:**
Once I added `<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />` in the `AndroidManifext.xml` and `setNotificationOpenedHandler` in the `App.js` in order to prevent `Open with` prompt for `launchUrl` and to handle deep link open the notifications link wouldn't open if the app is closed. Do you have some advice on how I can handle `launchUrl` differently and prevent `Open with` prompt once I want to use deep links inside the app, without losing the ability to open the link when the app is closed?

**Environment**
1. OneSignal React-Native SDK version: `4.0.4`
2. Added with `npm`

**Comment by BokiGaja** [comment] 2021-05-12 10:27
Also, the same issue appeared for the Android as mentioned in this issue:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/1312

**Comment by rgomezp** [comment] 2021-06-01 23:37
Duplicate of #OneSignal/OneSignal-Android-SDK#1312

**Closed as completed by rgomezp** 2021-06-01 23:37 UTC
