### ISSUE TITLE
Manifest merger failed with multiple errors

### ISSUE THREAD

**Issue by bunyaminmrcn** [OneSignal/react-native-onesignal#809] opened 2019-07-22 14:48 UTC
**Description:**

Hi people. I had some issues and solved them but i have one more. I added onesignal-gradle-plugin and configured with Firebase and Onesignal dashboard . Error happen while building project (Execution failed for task ':react-native-onesignal:processDebugAndroidTestManifest)

**Environment**

1. react-native : "0.60.4"
2. react-native-onesignal: "3.2.14"

**What i do:**

1. Linked onesignal and configure with dashboard
2. Changed  'onesignal_app_id' to my app_id from onesignal-dashboard
3. Gradle logs error like that
- requires a placeholder substitution but no value for <onesignal_app_id> is provided
- requires a placeholder substitution but no value for <onesignal_google_project_number> is provided
 

**Screenshot:**

![error1](https://user-images.githubusercontent.com/30148504/61641943-b6a10580-aca8-11e9-842f-5c155eaa444c.png)

**Thanks. Really need resolve issue:\**

**Comment by rgomezp** [comment] 2019-07-22 22:23
Duplicate of #777

**Closed as completed by rgomezp** 2019-07-22 22:23 UTC
