### ISSUE TITLE
Notification still received after clearing app data

### ISSUE THREAD

**Issue by dori871992** [OneSignal/react-native-onesignal#967] opened 2020-04-01 17:26 UTC
**Description:**

After clearing app data and cache on android (without logging out), the app is still capable of receiving notifications which is not the expected behaviour in this case. The only chance to prevent notification coming in is to call:  **OneSignal.removeExternalUserId()** (which will not be possible in this case since user is clearing the data directly from device settings) or by removing the event listener (which still cannot be triggered because we are outside of the app).

**Environment**

"react-native-onesignal": "^3.5.0"

**Steps to Reproduce Issue:**

1. On Device (1): Go to app info on android device and clear app data and cache
2. On Device (2): Send notification (message) to Device (1) and see that notification is still received.

**Comment by jkasten2** [comment] 2020-04-05 00:59
@dori871992 Thanks for reporting. I was able to reproduce this issue as well on a few devices:
* LG G7 with Android 9 (Pie) with the "Google Play Services" app version 20.09.75.
* Android 9 emulator with  "Google Play Services" app version 20.04.14. 
* Android 7.0 emulator with "Google Play Services" app version 17.7.43. 
* Android 4.4.2  emulator with "Google Play Services" app version 16.0.89.
* Android 4.1.2 emulator with "Google Play Services" app version 9.2.56.

I remember that this was not always the case, after the app's data is clear it would not get any more push notifications until the app has been reopened.
Since the push `Intent` get broadcasted from the  "Google Play Services" app my hypothesis is that there is a change here. Where it probably used to check if the target's app's data was just cleared before sending the broadcast.

If the above is correct is then it may have been a design decision Google made or a bug. Next steps would be to search for in Google's docs and any possible forums or support tickets. As well as collect system logcat logs that could confirm this.

Other observed behavior: When I pressed the "Clear data" button on our test app I noticed all notifications for the app were cleared.

I also checked the broadcasts log and Google Play services is still firing the broadcast.
```
adb shell
dumpsys activity broadcasts
```
```java
 Historical Broadcast #19:
    BroadcastRecord{a01329b0 com.google.android.c2dm.intent.RECEIVE}
    Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=com.onesignal.example (has extras) }
    caller=com.google.android.location 1772:com.google.process.gapps/u0a16 pid=1772 uid=10016
    dispatchClockTime=Sat Apr 04 18:32:13 PDT 2020
    dispatchTime=-6m17s46ms finishTime=-6m16s980ms
    resultAbort=false ordered=true sticky=false initialSticky=false
    nextReceiver=2 receiver=null
    state=0 (IDLE)
    Receiver #0: ResolveInfo{a01264e0 com.onesignal.GcmBroadcastReceiver p=999 o=0 m=0x108000}
      priority=999 preferredOrder=0 match=0x108000 specificIndex=-1 isDefault=false
      ActivityInfo:
        name=com.onesignal.GcmBroadcastReceiver
        packageName=com.onesignal.example
        enabled=true exported=true processName=com.onesignal.example
        permission=com.google.android.c2dm.permission.SEND
        taskAffinity=com.onesignal.example targetActivity=null
        ApplicationInfo:
          packageName=com.onesignal.example
          labelRes=0x0 nonLocalizedLabel=OneSignal Example icon=0x7f060069
          className=com.onesignal.example.OneSignalExampleApp
          processName=com.onesignal.example
          taskAffinity=com.onesignal.example
          uid=10048 flags=0x8bf46 theme=0x7f0d0005
          requiresSmallestWidthDp=0 compatibleWidthLimitDp=0 largestWidthLimitDp=0
          sourceDir=/data/app/com.onesignal.example-1.apk
          dataDir=/data/data/com.onesignal.example
          enabled=true targetSdkVersion=28
          supportsRtl=false
```

**Comment by jkasten2** [comment] 2020-04-05 02:30
Since this behavior is reproducible on an Android 9 and all the way back to Android 4.1.2 emulator with "Google Play Services" app version 9.2.56 then it looks unlikely this was behaving different at any point. It is still possible that this could be a backend change on Google's end, where it may have marked the push token for the app as unsubscribed when it got a "Clear data" event. Or I simply mis-remembered this behavior and push notifications have always worked after a "Clear data" action.

Pressing "Force stop" does stop push notifications however if you just looking to test some specific.

Since you will most likely see this same behavior when using FCM directly I am going to close this ticket as working as intended. If in testing you noticed a it working differently let us know and we can reopen this ticket.

**Closed as completed by jkasten2** 2020-04-05 02:30 UTC
Labels: Documentation, Android, Reproducible

**Comment by anniewey** [comment] 2021-12-23 05:03
Is there a way to stop the notification from coming in after clearing app data? Given that the use case is the same (clear data without logging out)
