### ISSUE TITLE
inFocusDisplaying not working on iOS

### ISSUE THREAD

**Issue by witalobenicio** [OneSignal/react-native-onesignal#996] opened 2020-05-25 23:17 UTC
**Description:**

Setting `OneSignal.inFocusDisplaying(0);` on iOS does not work. I still get notifications showing up in notification center.

**Environment**

react-native: 0.59.9
react-native-onesignal: 3.7.2

**Steps to Reproduce Issue:**

1. Just call `OneSignal.inFocusDisplaying(0);` after the app is running

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment] 2020-05-28 19:49
Duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/issues/666

**Closed as completed by rgomezp** 2020-05-28 19:49 UTC
