### ISSUE TITLE
ANR Input dispatching timed out (window's input channel is full)

### ISSUE THREAD

**Issue by UberMC** [OneSignal/react-native-onesignal#589] opened 2018-07-22 21:45 UTC
Input dispatching timed out (Waiting because the touched window's input channel is full. Outbound queue length: 1. Wait queue length: 52.)

Android 6.0 | 4 | 66.7%
-- | -- | --
Android 7.0 | 1 | 16.7%
Android 7.1 | 1 | 16.7%

P8 Lite (hwALE-H) | 1 | 16.7%
-- | -- | --
Moto G (3rd Gen) (osprey_uds) | 1 | 16.7%
ES550 (ES550) | 1 | 16.7%
Redmi 4X (santoni) | 1 | 16.7%
Xperia Z3 Dual (D6633) | 1 | 16.7%
Smart prime 7 (P809V50) | 1 | 16.7%

CrashStack
https://i.imgur.com/Jt1azHj.png

The "OSH_NetworkHandlerThread" (tid=15) thread is in waiting state.

"main" tid=1 Blocked 
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x752a0000 self=0xab3354d8
  | sysTid=8830 nice=-4 cgrp=default sched=0/0 handle=0xf7412b38
  | state=S schedstat=( 6396094705 772242646 7793 ) utm=501 stm=138 core=3 HZ=100
  | stack=0xff192000-0xff194000 stackSize=8MB
  | held mutexes=
  at com.onesignal.UserStateSynchronizer.getToSyncUserState (UserStateSynchronizer.java:115)
- waiting to lock <0x085b9f5b> (a com.onesignal.UserStatePushSynchronizer) held by thread 15
  at com.onesignal.UserStateSynchronizer.getRegistrationId (UserStateSynchronizer.java:31)
  at com.onesignal.OneSignalStateSynchronizer.getRegistrationId (OneSignalStateSynchronizer.java:123)
  at com.onesignal.OneSignal$3.complete (OneSignal.java:776)
  at com.onesignal.PushRegistratorAbstractGoogle.isValidProjectNumber (PushRegistratorAbstractGoogle.java:141)
  at com.onesignal.PushRegistratorAbstractGoogle.registerForPush (PushRegistratorAbstractGoogle.java:50)
  at com.onesignal.OneSignal.registerForPushToken (OneSignal.java:768)
  at com.onesignal.OneSignal.makeAndroidParamsRequest (OneSignal.java:802)
  at com.onesignal.OneSignal.startRegistrationOrOnSession (OneSignal.java:730)
  at com.onesignal.OneSignal.onAppFocus (OneSignal.java:1119)
  at com.onesignal.ActivityLifecycleHandler.handleFocus (ActivityLifecycleHandler.java:120)
  at com.onesignal.ActivityLifecycleHandler.onActivityResumed (ActivityLifecycleHandler.java:74)
  at com.onesignal.ActivityLifecycleListener.onActivityResumed (ActivityLifecycleListener.java:48)
  at android.app.Application.dispatchActivityResumed (Application.java:214)
  at android.app.Activity.onResume (Activity.java:1245)
  at com.facebook.react.ReactActivity.onResume (ReactActivity.java:63)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1266)
  at android.app.Activity.performResume (Activity.java:6446)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3129)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3170)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1420)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:150)
  at android.app.ActivityThread.main (ActivityThread.java:5621)
  at java.lang.reflect.Method.invoke! (Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:794)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:684)
"OSH_NetworkHandlerThread" tid=15 Waiting 
"OSH_NetworkHandlerThread" prio=5 tid=15 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x32c0a190 self=0xab336cc0
  | sysTid=9166 nice=0 cgrp=default sched=0/0 handle=0xdc46e930
  | state=S schedstat=( 17842027 3007963 37 ) utm=1 stm=0 core=1 HZ=100
  | stack=0xdc36c000-0xdc36e000 stackSize=1038KB
  | held mutexes=
  at java.lang.Object.wait! (Native method)
- waiting on <0x074c9ed3> (a java.lang.Object)
  at java.lang.Thread.join (Thread.java:739)
- locked <0x074c9ed3> (a java.lang.Object)
  at com.onesignal.OneSignalRestClient.makeRequest (OneSignalRestClient.java:110)
  at com.onesignal.OneSignalRestClient.postSync (OneSignalRestClient.java:86)
  at com.onesignal.UserStateSynchronizer.doCreateOrNewSession (UserStateSynchronizer.java:283)
  at com.onesignal.UserStateSynchronizer.internalSyncUserState (UserStateSynchronizer.java:191)
  at com.onesignal.UserStateSynchronizer.syncUserState (UserStateSynchronizer.java:160)
- locked <0x085b9f5b> (a com.onesignal.UserStatePushSynchronizer)
  at com.onesignal.UserStateSynchronizer$NetworkHandlerThread$1.run (UserStateSynchronizer.java:69)
  at android.os.Handler.handleCallback (Handler.java:743)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:150)
  at android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by Nightsd01** [comment] 2018-07-26 17:51
Hi @UberMC , thanks for your detailed bug report. We believe that this issue is caused by the same root issue that causes #587, so I will be closing this one as a duplicate. We'll be investigating the problem today!

**Closed as completed by Nightsd01** 2018-07-26 17:51 UTC
