### ISSUE TITLE
OneSignal.logoutEmail still receives notification directed to registered email

### ISSUE THREAD

**Issue by marcoskoch** [OneSignal/react-native-onesignal#1001] opened 2020-06-09 13:45 UTC
**Description:**

In my app I use OneSignal's setEmail, at logout the logoutEmail function does not work. Even after calling her, I still receive notifications directed to the registered email

**Environment**

node: 10.16.3
yarn: 1.22.4
react-native: 0.60.4
react-native-onesignal: 3.7.3

**Steps to Reproduce Issue:**

1. After successful configuration of OneSignal, setEmail at login
1. Test with notification directed to the logged email
1. Call OneSignal.logoutEmail, as per the documentation at logout
1. Send targeted notification to email

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment] 2020-06-16 00:06
Howdy,
Thank you for letting us know. We will look into this issue. 

In the meantime, an alternative is you can set and unset the email as a tag.

Duplicate of https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/239

**Comment by rgomezp** [comment] 2020-10-02 21:57
To clarify, are you seeing this issue in Android or iOS or both? @marcoskoch 

Thanks

**Comment by marcoskoch** [comment] 2020-10-06 14:23
Hi @rgomezp, this situation occurs in both

**Comment by rgomezp** [comment] 2020-10-14 20:52
For visibility, I tested this using the `RNOneSignal` example app with the following metro bundler logs:

```
 LOG  Running "RNOneSignal" with {"rootTag":11,"initialProps":{}}
 LOG  Mounted!
 LOG  OneSignal permission: true
 LOG  Attempting to set email: test@go.co
 LOG  OneSignal: email subscription changed:  {"emailAddress": "test@go.co", "emailUserId": "336b180d-7e87-4c77-87cc-d0c3f3fa7737"}
 LOG  Success setting email: test@go.co
 LOG  Attempting to set external user id: ro2
 LOG  Results of setting external user id
 LOG  {"email": {"success": 1}, "push": {"success": 1}}
 LOG  Attempting to logout email
 LOG  OneSignal: email subscription changed:  {"emailAddress": null, "emailUserId": null}
```

In the dashboard, I see the following:
![Screen Shot 2020-10-14 at 3 51 41 PM](https://user-images.githubusercontent.com/11739227/96043845-2f075f80-0e35-11eb-85d5-14614c5a68bb.png)

I haven't tested targeting the email after, but at least I can confirm there is currently no visible change occurring in the dashboard following calling the `logoutEmail` function.

**Comment by rgomezp** [comment] 2020-11-13 23:50
Howdy y'all,
This issue should now be resolved. If you are still encountering issues, please continue discussion in https://github.com/OneSignal/OneSignal-iOS-SDK/issues/768

Enjoy!

**Closed as completed by rgomezp** 2020-11-13 23:50 UTC
Labels: Possible Bug
