### ISSUE TITLE
Apns Delegate Never Fired

### ISSUE THREAD

**Issue by Luckygirlllll** [OneSignal/react-native-onesignal#880] opened 2019-10-17 09:57 UTC
**Description:**

I'm getting an error in IOS 13, Apns Delegate Never Fired

(your description here)

**Environment**

1.  "^3.4.2",
2. npm

**Steps to Reproduce Issue:**

  1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK in the iOS AppDelegate
  3. Attempt to receive a push notification
4. See error in OneSignal dashboard

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Luckygirlllll** [comment] 2019-10-17 10:19
I noticed that this error occurs, when I'm trying to send Push Notification on the app which was build on the phone through Xcode, if I'm testing the app through TestFlight I'm not getting such error and can get Push Notification.

**Comment by rgomezp** [comment] 2019-10-21 21:40
Which physical device are you testing on?

**Comment by Luckygirlllll** [comment] 2019-10-22 09:06
Iphone 7 plus

**Comment by rgomezp** [comment] 2019-10-22 21:52
Duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/issues/503

Please follow the issue there

**Closed as completed by rgomezp** 2019-10-22 21:52 UTC
Labels: Help Wanted
