### ISSUE TITLE
Is there a way to trigger a handler on every notification received with sdk v4 ?

### ISSUE THREAD

**Issue by scesbron** [OneSignal/react-native-onesignal#1183] opened 2021-03-09 17:41 UTC
**Description:**

I am in the process of migrating my application from the sdk 3.9.3 to version 4.0.5. With the 3.x version I was able to do something on every notification received with 

```javascript
OneSignal.addEventListener('received', this.onNotificationReceived);
```

I replaced that with

```javascript
OneSignal.setNotificationWillShowInForegroundHandler(this.onNotificationReceived);
```

but if I correctly understand the doc this new handler is only triggered when the app has the focus.

The previous received event listener was practical because with it I can load some data based on the type of message I received.

Is there a way with the latest sdk 4.x to call an application callback every time the phone receive a message ?

**Environment**

I am using the 4.0.5 version, before my migration I was using the 3.9.3 version

**Steps to Reproduce Issue:**

1. open the app
1. put another app in the foreground
1. send a push notification to the app
1. my receive handler is not called

**Comment by sunweiyang** [comment] 2021-03-10 18:36
I also need this. Looking at the available methods, I don't see any that corresponds to notification received.

**Comment by rgomezp** [comment] 2021-03-30 22:15
Howdy,
That is correct.

We will see if we can add this soon.

**Comment by rgomezp** [comment] 2021-03-30 22:39
Duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1154

**Closed as completed by rgomezp** 2021-03-30 22:39 UTC
Labels: Enhancement / Feature
