### ISSUE TITLE
SDK v4.0.4  Android  app always shows silent notifications regardless of notifReceivedEvent.complete(notif); 

### ISSUE THREAD

**Issue by nkaramarko** [OneSignal/react-native-onesignal#1175] opened 2021-02-21 20:43 UTC
**Description:**

IOS notifcations work perfectly but on Android they are always silent, whether app is in foreground or background.
 notifReceivedEvent.complete(notif); doesnt change anything.
I want to be able to show push notification, especially when the app is in background.

**Environment**

I installed the latest version 4.0.4 with yarn.
Tested on devices:
Xiaomi redmi note 7, Android OS 9
Huawei P30 pro, Android OS 10

**Steps to Reproduce Issue:**

 
 1. install SDK 4.0.4, follow guide as per newest documentation.
 2. send push notification from https://app.onesignal.com/ Messaging tool
 3. notification arrives, but it is always silent
 4. i have all the correct settings in the phone settings to show the notification
 5. i tried  notifReceivedEvent.complete(notif) inside setNotificationWillShowInForegroundHandler but it doesnt help

**Comment by santoshD93** [comment] 2021-04-21 11:08
I am facing the same issue for Android devices.

The iOS app works perfectly.

**Comment by rgomezp** [comment] 2021-04-21 22:35
Duplicate of #1149

**Closed as completed by rgomezp** 2021-04-21 22:35 UTC
